apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed
  namespace: default
  labels:
    app: feed
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: feed
  template:
    metadata:
      labels:
        pod: feed
    spec:
      containers:
        - name: feed
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 7000
          resources: { }
          env:
            - name: middleware_check_user_url
              value: http://middleware-service:6000/middleware/check_user
            - name: middleware_check_course_url
              value: http://middleware-service:6000/middleware/check_course
            - name: middleware_check_lesson_url
              value: http://middleware-service:6000/middleware/check_lesson
            - name: middleware_check_homework_url
              value: http://middleware-service:6000/middleware/check_homework

            - name: POSTGRES_DB
              value: eduonedbfeed
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres.acid-minimal-cluster-feed.credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.acid-minimal-cluster-feed.credentials
                  key: password

            - name: POSTGRES_PORT
              value: "5432"

            - name: POSTGRES_HOST
              value: acid-minimal-cluster-feed

            - name: DB_ENGINE
              value: postgresql+asyncpg

            - name: ELASTIC_HOST
              value: elasticsearch.kube-logging

      imagePullSecrets:
        - name: gitlab-regcred

      restartPolicy: Always
